### ISSUE TITLE
GetString存在数组越界问题

### ISSUE THREAD

**Issue by qingliu-cyl** [0x1un/go-dmidecode#1]
smbios/structure.go
异常位置：func (s *Structure) GetString(offset int) string 
当s为如下值时， 获取SerialNumaer(offset=12)， .Strings[index-1]会数组越界
```go
s := &smbios.Structure{
		Header: smbios.Header{
			Type: 4,
			Length: 48,
			Handle: 32,
		},
		Formatted: []byte{1,3,1,2,17,15,144,0,255,251,139,23,3,138,100,0,228,12,
			252,8,65,55,29,0,30,0,31,0,4,5,6,32,32,64,252,0,1,0,32,0,32,0,64,0},
		Strings: []string{
			"CPU0",
			"Chengdu Hygon",
			"Hygon C86 7291 32-core Processor",
		},
	}
```
PS： 在浪潮的设备上发现了这个问题

**Comment by 0x1un** [comment]
你好，你是如何使用的，完整的报错信息也提供一下。

**Comment by qingliu-cyl** [comment]
> 你好，你是如何使用的，完整的报错信息也提供一下。

抱歉， 设备已经没了， 上面就是出错时采集到的数据， 将数据代入可以复现， 获取SerialNumaer时 GetString(0x1c)的时候会数组越界直接panic

**Comment by 0x1un** [comment]
看起来是因为只获取到了这三个信息，这种报错在您那有很多吗；当初我用这个库在上万台的设备上运行过，确实没有遇到这种情况；或许我应该给它加一点可以容忍这种情况的判断。
